# This workflow will publish a package to GitHub Packages when a release is created

name: Ngx-Passwordy Package

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lib:build
      - run: npm run lib:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}