# This workflow will test the library whenever a pull request is submmitted for the main branch

name: Test Ngx-passwordy

on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: SetUp
        run: npm i
        
      - name: Build Library
        run: npm run lib:build
      
      - name: Test Library
        run: npm run lib:test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
